#!/bin/bash
# Pre-create CDC topics on 3-broker cluster (replication factor 3)
# Run from project root: ./docker/scripts/precreate-topics.sh

set -e

BOOTSTRAP="localhost:9092"
# -e KAFKA_OPTS=: broker sets JMX agent; CLI JVM must not reuse same metrics port
KAFKA_TOPICS="docker exec -e KAFKA_OPTS= kafka1 kafka-topics"
# Alternative if kafka-topics not in PATH: docker exec kafka1 /usr/bin/kafka-topics

echo "Pre-creating CDC topics (replication-factor=3)..."

for topic in __orcl-schema-changes.racdb __cflt-oracle-heartbeat.racdb \
  racdb.ORDERMGMT.REGIONS racdb.ORDERMGMT.COUNTRIES racdb.ORDERMGMT.LOCATIONS \
  racdb.ORDERMGMT.WAREHOUSES racdb.ORDERMGMT.EMPLOYEES racdb.ORDERMGMT.PRODUCT_CATEGORIES \
  racdb.ORDERMGMT.PRODUCTS racdb.ORDERMGMT.CUSTOMERS racdb.ORDERMGMT.CONTACTS \
  racdb.ORDERMGMT.ORDERS racdb.ORDERMGMT.ORDER_ITEMS racdb.ORDERMGMT.INVENTORIES \
  racdb.ORDERMGMT.NOTES racdb.ORDERMGMT.MTX_TRANSACTION_ITEMS \
  racdb.ORDERMGMT.MBK_BANK_DETAILS racdb.ORDERMGMT.MTX_BNSART_RANGE_DETAILS racdb.ORDERMGMT.MTX_BATCH_PAYMENT \
  racdb.ORDERMGMT.MTX_USER_BANK_SWEEP_DTLS racdb.ORDERMGMT.MBK_CUST_ACCOUNTS racdb.ORDERMGMT.MTX_BATCHES \
  racdb.ORDERMGMT.MTX_BNSART_RANGE racdb.ORDERMGMT.SENTSMS racdb.ORDERMGMT.MTX_TRANSACTION_APPROVAL \
  racdb.ORDERMGMT.MTX_AMBIGUOUS_TXN_DETAILS racdb.ORDERMGMT.EXTERNAL_TRANSACTION_LOG racdb.ORDERMGMT.MTX_PARTY_ACCESS \
  racdb.ORDERMGMT.MTX_PARTY racdb.ORDERMGMT.USERS racdb.ORDERMGMT.MTX_ADMIN_AUDIT_TRAIL racdb.ORDERMGMT.MTX_AUDIT_TRAIL \
  racdb.ORDERMGMT.MTX_PARTY_BARRED_HIST racdb.ORDERMGMT.MTX_COMMISSION_RANGE racdb.ORDERMGMT.MTX_COMMISSION_RANGE_DETAILS \
  racdb.ORDERMGMT.MTX_TRANSACTION_HEADER_META racdb.ORDERMGMT.SYS_SERVICE_TYPES racdb.ORDERMGMT.MTX_SERVICE_CHARGE \
  racdb.ORDERMGMT.MTX_SERVICE_CHARGE_RANGE racdb.ORDERMGMT.MTX_SERV_CHRG_RANGE_DETAILS racdb.ORDERMGMT.MTX_PARTY_BLACK_LIST \
  racdb.ORDERMGMT.MNY_ONFLY_REG_DETAIL racdb.ORDERMGMT.MTX_CHURN_USERS racdb.ORDERMGMT.MTX_TRANSACTION_HEADER \
  racdb.ORDERMGMT.MTX_WALLET racdb.ORDERMGMT.MTX_WALLET_BALANCES \
  racdb.XSTRPDB.ORDERMGMT.REGIONS racdb.XSTRPDB.ORDERMGMT.MTX_TRANSACTION_ITEMS \
  racdb.TPCC.DISTRICT racdb.TPCC.CUSTOMER racdb.TPCC.HISTORY \
  racdb.TPCC.ITEM racdb.TPCC.WAREHOUSE racdb.TPCC.STOCK \
  racdb.TPCC.ORDERS racdb.TPCC.NEW_ORDER racdb.TPCC.ORDER_LINE; do
  $KAFKA_TOPICS --bootstrap-server $BOOTSTRAP --create --if-not-exists \
    --topic "$topic" --partitions 1 --replication-factor 3 2>/dev/null || true
done

echo "Done."
