-- =============================================================================
-- Oracle XStream CDC - Step 3: Configure Supplemental Logging
-- Run as SYSDBA
-- Requires: 01-create-sample-schema.sql (ORDERMGMT tables must exist)
-- =============================================================================

-- 1. Enable minimal supplemental logging (prerequisite)
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

-- 2a. For POC: Enable supplemental logging for specific tables (RECOMMENDED)
-- Tables from 01-create-sample-schema.sql (ORDERMGMT schema)
ALTER SESSION SET CONTAINER = XSTRPDB;

ALTER TABLE ORDERMGMT.REGIONS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ORDERMGMT.COUNTRIES ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ORDERMGMT.LOCATIONS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ORDERMGMT.WAREHOUSES ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ORDERMGMT.EMPLOYEES ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ORDERMGMT.PRODUCT_CATEGORIES ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ORDERMGMT.PRODUCTS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ORDERMGMT.CUSTOMERS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ORDERMGMT.CONTACTS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ORDERMGMT.ORDERS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ORDERMGMT.ORDER_ITEMS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ORDERMGMT.INVENTORIES ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ORDERMGMT.NOTES ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- 2b. OR: Enable for entire database (use with caution - more redo generated)
-- ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- 3. Verify supplemental logging
SELECT SUPPLEMENTAL_LOG_DATA_MIN, SUPPLEMENTAL_LOG_DATA_ALL FROM V$DATABASE;
