-- =============================================================================
-- Insert test rows into MTX_TRANSACTION_ITEMS for CDC verification
-- Run as: sqlplus ordermgmt/<pwd>@//racdb-scan...:1521/XSTRPDB... @14-insert-mtx-transaction-items.sql
-- After running: check Kafka topic racdb.ORDERMGMT.MTX_TRANSACTION_ITEMS
-- Uses timestamp-based UNIQUE_SEQ_NUMBER so each run inserts new rows (no PK collision).
-- =============================================================================

INSERT INTO ORDERMGMT.MTX_TRANSACTION_ITEMS (
  TRANSFER_ID, PARTY_ID, USER_TYPE, ENTRY_TYPE, ACCOUNT_ID,
  TRANSFER_DATE, TRANSACTION_TYPE, SECOND_PARTY, PROVIDER_ID,
  TXN_SEQUENCE_NUMBER, PAYMENT_TYPE_ID, SECOND_PARTY_PROVIDER_ID, UNIQUE_SEQ_NUMBER,
  REQUESTED_VALUE, APPROVED_VALUE, TRANSFER_STATUS
) VALUES (
  'TRF001', 'P001', 'REG', 'DR', 'ACC001',
  SYSDATE, 'TRANS', 'P002', 1,
  1001, 1, 1, 'SEQ-MTX-001-' || TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS'),
  1000, 1000, 'COM'
);

INSERT INTO ORDERMGMT.MTX_TRANSACTION_ITEMS (
  TRANSFER_ID, PARTY_ID, USER_TYPE, ENTRY_TYPE, ACCOUNT_ID,
  TRANSFER_DATE, TRANSACTION_TYPE, SECOND_PARTY, PROVIDER_ID,
  TXN_SEQUENCE_NUMBER, PAYMENT_TYPE_ID, SECOND_PARTY_PROVIDER_ID, UNIQUE_SEQ_NUMBER,
  REQUESTED_VALUE, APPROVED_VALUE, TRANSFER_STATUS
) VALUES (
  'TRF002', 'P002', 'REG', 'CR', 'ACC002',
  SYSDATE, 'TRANS', 'P001', 1,
  1002, 1, 1, 'SEQ-MTX-002-' || TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS'),
  500, 500, 'COM'
);

INSERT INTO ORDERMGMT.MTX_TRANSACTION_ITEMS (
  TRANSFER_ID, PARTY_ID, USER_TYPE, ENTRY_TYPE, ACCOUNT_ID,
  TRANSFER_DATE, TRANSACTION_TYPE, SECOND_PARTY, PROVIDER_ID,
  TXN_SEQUENCE_NUMBER, PAYMENT_TYPE_ID, SECOND_PARTY_PROVIDER_ID, UNIQUE_SEQ_NUMBER,
  REQUESTED_VALUE, APPROVED_VALUE, TRANSFER_STATUS, USER_NAME
) VALUES (
  'TRF003', 'P003', 'REG', 'DR', 'ACC003',
  SYSDATE, 'TRANS', 'P001', 1,
  1003, 1, 1, 'SEQ-MTX-003-' || TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS'),
  250, 250, 'PEN', 'TestUser'
);

COMMIT;

PROMPT Inserted 3 rows. Verify CDC topic:
PROMPT   docker exec -e KAFKA_OPTS= kafka1 kafka-console-consumer --bootstrap-server kafka1:29092 --topic racdb.ORDERMGMT.MTX_TRANSACTION_ITEMS --from-beginning --max-messages 5
