-- =============================================================================
-- UG Prod Tables - CDC Load Generator
-- Run as: sqlplus ordermgmt/<pwd>@//host:1521/XSTRPDB @17-generate-ug-prod-cdc-load.sql
-- Or: ./run-generate-ug-prod-cdc-load.sh
--
-- Inserts minimal test rows into UG prod tables to populate Kafka topics.
-- Use unique IDs per run (timestamp-based) to avoid PK collisions.
-- =============================================================================

SET SERVEROUTPUT ON
SET TIMING ON

COLUMN run_id NEW_VALUE v_suffix
SELECT TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS') AS run_id FROM DUAL;

PROMPT Generating CDC load for UG prod tables (suffix: &v_suffix)...
PROMPT

-- MBK_BANK_DETAILS
INSERT INTO ORDERMGMT.MBK_BANK_DETAILS (BANK_ID, BANK_NAME, BANK_TYPE) 
VALUES ('BANK'||'&v_suffix', 'Test Bank', 'MOBILE');

-- SYS_SERVICE_TYPES
INSERT INTO ORDERMGMT.SYS_SERVICE_TYPES (SERVICE_TYPE, SERVICE_NAME) 
VALUES ('SVC'||'&v_suffix', 'Test Service');

-- MTX_AMBIGUOUS_TXN_DETAILS
INSERT INTO ORDERMGMT.MTX_AMBIGUOUS_TXN_DETAILS (TRANSFER_ID, TRANSFER_STATUS) 
VALUES ('TRF'||'&v_suffix', 'PEN');

-- MTX_SERVICE_CHARGE
INSERT INTO ORDERMGMT.MTX_SERVICE_CHARGE (
  SERVICE_CHARGE_ID, PAYER_PROVIDER_ID, PAYEE_PROVIDER_ID,
  CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON
) VALUES (1000000 + MOD(&v_suffix, 100000), 1, 1, 'sys', SYSDATE, 'sys', SYSDATE);

-- MTX_BNSART_RANGE_DETAILS
INSERT INTO ORDERMGMT.MTX_BNSART_RANGE_DETAILS (BNSART_RANGE_ID) 
VALUES (1000000 + MOD(&v_suffix, 100000));

-- MTX_BNSART_RANGE
INSERT INTO ORDERMGMT.MTX_BNSART_RANGE (BNSART_RANGE_ID, SLAB_CODE, PAYEE_PROVIDER_ID) 
VALUES (1000000 + MOD(&v_suffix, 100000), 1, 1);

-- MTX_SERV_CHRG_RANGE_DETAILS
INSERT INTO ORDERMGMT.MTX_SERV_CHRG_RANGE_DETAILS (SERVICE_CHARGE_RANGE_ID) 
VALUES (1000000 + MOD(&v_suffix, 100000));

-- MTX_SERVICE_CHARGE_RANGE
INSERT INTO ORDERMGMT.MTX_SERVICE_CHARGE_RANGE (SERVICE_CHARGE_RANGE_ID, SLAB_CODE) 
VALUES (1000000 + MOD(&v_suffix, 100000), 1);

-- MTX_COMMISSION_RANGE_DETAILS
INSERT INTO ORDERMGMT.MTX_COMMISSION_RANGE_DETAILS (COMMISSION_RANGE_ID) 
VALUES (1000000 + MOD(&v_suffix, 100000));

-- MTX_COMMISSION_RANGE
INSERT INTO ORDERMGMT.MTX_COMMISSION_RANGE (
  COMMISSION_RANGE_ID, SLAB_CODE, PAYER_PROVIDER_ID, PAYEE_PROVIDER_ID,
  PAYER_PAYMENT_METHOD_TYPE, PAYEE_PAYMENT_METHOD_TYPE
) VALUES (1000000 + MOD(&v_suffix, 100000), 1, 1, 1, 'WALLET', 'WALLET');

-- MTX_PARTY
INSERT INTO ORDERMGMT.MTX_PARTY (USER_ID, NETWORK_CODE, CATEGORY_CODE, PARENT_ID, OWNER_ID, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES ('UP'||'&v_suffix', '01', 'REG', 'P001', 'P001', 'sys', SYSDATE, 'sys', SYSDATE);

-- USERS
INSERT INTO ORDERMGMT.USERS (USER_ID, USER_NAME, NETWORK_CODE, CATEGORY_CODE, PARENT_ID, OWNER_ID, CREATED_BY, CREATED_ON)
VALUES ('U'||'&v_suffix', 'User'||'&v_suffix', '01', 'REG', 'P001', 'P001', 'sys', SYSDATE);

-- MTX_TRANSACTION_APPROVAL
INSERT INTO ORDERMGMT.MTX_TRANSACTION_APPROVAL (TRANSFER_ID, ACTION, ACTION_ON)
VALUES ('TRF'||'&v_suffix', 'APR', SYSDATE);

-- EXTERNAL_TRANSACTION_LOG
INSERT INTO ORDERMGMT.EXTERNAL_TRANSACTION_LOG (REFERENCE_ID, TRANSACTION_ID, INBOUND_OUTBOUND, TRANSACTION_STATUS, TRANSACTION_DATE)
VALUES ('REF'||'&v_suffix', 'TXN'||'&v_suffix', 'IN', 'SUCCESS', SYSDATE);

-- MTX_PARTY_ACCESS
INSERT INTO ORDERMGMT.MTX_PARTY_ACCESS (
  USER_PHONES_ID, MSISDN, USER_ID, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,
  PREFIX_ID, PROVIDER_ID, LEVEL2_APPROVED_BY, LEVEL2_APPROVED_ON
) VALUES (1000000 + MOD(&v_suffix, 100000), '265'||SUBSTR('&v_suffix',-7), 'UP'||'&v_suffix', 'sys', SYSDATE, 'sys', SYSDATE, 1, 1, 'sys', SYSDATE);

-- MBK_CUST_ACCOUNTS
INSERT INTO ORDERMGMT.MBK_CUST_ACCOUNTS (CUST_ID, ACCOUNT_NO, STATUS_ID, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON, SN, PROVIDER_ID)
VALUES ('C'||'&v_suffix', 'ACC'||'&v_suffix', '01', 'sys', SYSDATE, 'sys', SYSDATE, 1000000 + MOD(&v_suffix, 100000), 1);

-- MTX_BATCHES
INSERT INTO ORDERMGMT.MTX_BATCHES (BATCH_ID, NETWORK_CODE, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES ('BAT'||'&v_suffix', '01', 'sys', SYSDATE, 'sys', SYSDATE);

-- MTX_BATCH_PAYMENT
INSERT INTO ORDERMGMT.MTX_BATCH_PAYMENT (
  PAYER_PROVIDER_ID, PAYEE_PROVIDER_ID, PAYER_WALLET_TYPE_ID, PAYEE_WALLET_TYPE_ID,
  PAYER_MSISDN, PAYEE_MSISDN, AMOUNT, BATCH_ID, BATCH_SEQUENCE_NUMBER, SERVICE_TYPE, CREATED_ON
) VALUES (1, 1, 1, 1, '2651111111', '2652222222', 100, 'BAT'||'&v_suffix', 1, 'TRANS', SYSDATE);

-- MNY_ONFLY_REG_DETAIL
INSERT INTO ORDERMGMT.MNY_ONFLY_REG_DETAIL (TXN_ID, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON, PROVIDER_ID, PAYMENT_TYPE_ID)
VALUES ('TXN'||'&v_suffix', 'sys', SYSDATE, 'sys', SYSDATE, 1, 1);

-- MTX_TRANSACTION_HEADER
INSERT INTO ORDERMGMT.MTX_TRANSACTION_HEADER (TRANSFER_ID, TRANSFER_DATE, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES ('TRF'||'&v_suffix', SYSDATE, 'sys', SYSTIMESTAMP, 'sys', SYSTIMESTAMP);

-- MTX_TRANSACTION_ITEMS (same TRANSFER_ID as header; UNIQUE_SEQ_NUMBER is PK)
INSERT INTO ORDERMGMT.MTX_TRANSACTION_ITEMS (
  TRANSFER_ID, PARTY_ID, USER_TYPE, ENTRY_TYPE, ACCOUNT_ID,
  TRANSFER_DATE, TRANSACTION_TYPE, SECOND_PARTY, PROVIDER_ID,
  TXN_SEQUENCE_NUMBER, PAYMENT_TYPE_ID, SECOND_PARTY_PROVIDER_ID, UNIQUE_SEQ_NUMBER,
  REQUESTED_VALUE, APPROVED_VALUE, TRANSFER_STATUS
) VALUES (
  'TRF'||'&v_suffix', 'P001', 'REG', 'DR', 'ACC001',
  SYSDATE, 'TRANS', 'P002', 1,
  1001, 1, 1, 'SEQ-MTX-1-'||'&v_suffix',
  1000, 1000, 'COM'
);

INSERT INTO ORDERMGMT.MTX_TRANSACTION_ITEMS (
  TRANSFER_ID, PARTY_ID, USER_TYPE, ENTRY_TYPE, ACCOUNT_ID,
  TRANSFER_DATE, TRANSACTION_TYPE, SECOND_PARTY, PROVIDER_ID,
  TXN_SEQUENCE_NUMBER, PAYMENT_TYPE_ID, SECOND_PARTY_PROVIDER_ID, UNIQUE_SEQ_NUMBER,
  REQUESTED_VALUE, APPROVED_VALUE, TRANSFER_STATUS
) VALUES (
  'TRF'||'&v_suffix', 'P002', 'REG', 'CR', 'ACC002',
  SYSDATE, 'TRANS', 'P001', 1,
  1002, 1, 1, 'SEQ-MTX-2-'||'&v_suffix',
  500, 500, 'COM'
);

INSERT INTO ORDERMGMT.MTX_TRANSACTION_ITEMS (
  TRANSFER_ID, PARTY_ID, USER_TYPE, ENTRY_TYPE, ACCOUNT_ID,
  TRANSFER_DATE, TRANSACTION_TYPE, SECOND_PARTY, PROVIDER_ID,
  TXN_SEQUENCE_NUMBER, PAYMENT_TYPE_ID, SECOND_PARTY_PROVIDER_ID, UNIQUE_SEQ_NUMBER,
  REQUESTED_VALUE, APPROVED_VALUE, TRANSFER_STATUS, USER_NAME
) VALUES (
  'TRF'||'&v_suffix', 'P003', 'REG', 'DR', 'ACC003',
  SYSDATE, 'TRANS', 'P001', 1,
  1003, 1, 1, 'SEQ-MTX-3-'||'&v_suffix',
  250, 250, 'PEN', 'TestUser'
);

-- MTX_TRANSACTION_HEADER_META
INSERT INTO ORDERMGMT.MTX_TRANSACTION_HEADER_META (TRANSFER_ID) VALUES ('TRF'||'&v_suffix');

-- MTX_WALLET
INSERT INTO ORDERMGMT.MTX_WALLET (WALLET_NUMBER, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON, PAYMENT_TYPE_ID, PROVIDER_ID)
VALUES ('WL'||'&v_suffix', 'sys', SYSDATE, 'sys', SYSDATE, 1, 1);

-- MTX_WALLET_BALANCES
INSERT INTO ORDERMGMT.MTX_WALLET_BALANCES (WALLET_NUMBER, WALLET_SEQUENCE_NUMBER, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON, PROVIDER_ID, PAYMENT_TYPE_ID)
VALUES ('WL'||'&v_suffix', 0, 'sys', SYSDATE, 'sys', SYSDATE, 1, 1);

-- SENTSMS
INSERT INTO ORDERMGMT.SENTSMS (ID, DELIVEREDON) VALUES ('SMS'||'&v_suffix', SYSDATE);

-- MTX_USER_BANK_SWEEP_DTLS
INSERT INTO ORDERMGMT.MTX_USER_BANK_SWEEP_DTLS (USER_ID, BANK_ACCOUNT_ID, STATUS, CREATED_BY, CREATED_ON)
VALUES ('U'||'&v_suffix', 'ACC'||'&v_suffix', 'A', 'sys', SYSDATE);

-- MTX_PARTY_BARRED_HIST
INSERT INTO ORDERMGMT.MTX_PARTY_BARRED_HIST (SN, USER_NAME, PARENT_NAME, CATEGORY_CODE, CATEGORY_NAME, MSISDN, PROVIDER_ID)
VALUES (1000000 + MOD(&v_suffix, 100000), 'TestUser', 'TestParent', 'REG', 'Regular', '2651111111', 1);

-- MTX_PARTY_BLACK_LIST
INSERT INTO ORDERMGMT.MTX_PARTY_BLACK_LIST (BLACK_LIST_TYPE_ID, TYPE, GRPH_DOMAIN_CODE, PARTY_ID, ACCESS_TYPE, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, PROVIDER_ID)
VALUES ('BL'||'&v_suffix', 'FRAUD', 'MW', 'P'||'&v_suffix', 'PHONE', SYSDATE, 'sys', SYSDATE, 'sys', 1);

-- MTX_CHURN_USERS
INSERT INTO ORDERMGMT.MTX_CHURN_USERS (BATCH_ID, USER_ID, MSISDN, STATUS, CREATED_BY, CREATED_ON, PAYMENT_TYPE_ID, SEQUENCE_ID)
VALUES ('CH'||'&v_suffix', 'U'||'&v_suffix', '2651111111', 'PEN', 'sys', SYSDATE, '1', 1000000 + MOD(&v_suffix, 100000));

-- MTX_ADMIN_AUDIT_TRAIL
INSERT INTO ORDERMGMT.MTX_ADMIN_AUDIT_TRAIL (SN) VALUES ('A'||'&v_suffix');

-- MTX_AUDIT_TRAIL
INSERT INTO ORDERMGMT.MTX_AUDIT_TRAIL (SN) VALUES ('T'||'&v_suffix');

COMMIT;

PROMPT Inserted test rows. CDC should flow to racdb.ORDERMGMT.* topics within 10-30 seconds.
PROMPT Kafka topic pattern: racdb.ORDERMGMT.<TABLE> (not racdb.XSTRPDB.ORDERMGMT.*).
PROMPT On Connect VM: ./docker/scripts/check-ordermgmt-mtx-kafka-offsets.sh
