ALTER SESSION SET CONTAINER = XSTRPDB;
SET LINESIZE 200 PAGESIZE 80
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

-- Redo generated by ORDERMGMT sessions (counter since each session started)
SELECT s.sid, s.serial#, SUBSTR(s.program, 1, 60) AS program,
       ROUND(st.value / 1024 / 1024, 2) AS redo_mb
FROM v$session s
JOIN v$sesstat st ON s.sid = st.sid
JOIN v$statname sn ON st.statistic# = sn.statistic#
WHERE sn.name = 'redo size'
  AND s.username = 'ORDERMGMT'
ORDER BY st.value DESC;

-- Cumulative instance redo size (sysstat)
SELECT name, ROUND(value / 1024 / 1024 / 1024, 2) AS redo_gb
FROM v$sysstat
WHERE name = 'redo size';

EXIT;
