-- Quick test insert into UG prod tables (run as SYSDBA or ordermgmt)
ALTER SESSION SET CONTAINER = XSTRPDB;

INSERT INTO ORDERMGMT.MBK_BANK_DETAILS (BANK_ID, BANK_NAME, BANK_TYPE) 
VALUES ('BANK' || TO_CHAR(SYSDATE,'HH24MISS'), 'CDC Test Bank', 'MOBILE');

INSERT INTO ORDERMGMT.SYS_SERVICE_TYPES (SERVICE_TYPE, SERVICE_NAME) 
VALUES ('SVC' || TO_CHAR(SYSDATE,'HH24MISS'), 'CDC Test Service');

INSERT INTO ORDERMGMT.MTX_AMBIGUOUS_TXN_DETAILS (TRANSFER_ID, TRANSFER_STATUS) 
VALUES ('TRF' || TO_CHAR(SYSDATE,'HH24MISS'), 'PEN');

COMMIT;
PROMPT Inserted 3 test rows. Check Kafka topics.
EXIT;
